image: nfcore/gitpod:latest

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
